Chloropleth Integration
hack4impact-uiuc/communityconnect-labs pull request #12
Opened 2019-10-23 01:17 UTC by meghatron3000

# Description

This PR adds a sample chloropleth layer onto our current map. The chloropleth currently uses states as boundaries and is based off of the sample data given in the chloropleth tutorial by Mapbox. Our next steps are to try and incorporate tracts as boundaries and the ccl data into our chloropleth.

# Screenshots: 
*Zoomed Out*
<img width="1280" alt="Screen Shot 2019-10-22 at 8 07 44 PM" src="https://user-images.githubusercontent.com/6444825/67347773-a9462200-f508-11e9-8e21-5b77be43b189.png">

*Zoomed In*
<img width="1280" alt="Screen Shot 2019-10-22 at 8 07 44 PM" src="https://user-images.githubusercontent.com/6444825/67347784-b531e400-f508-11e9-83a7-dde27f6980f0.png">

2019-10-23 01:21 UTC, chyku commented
its a CHOROPLETH not CHLOROPLETH _please_

2019-10-30 04:49 UTC, chyku requested changes
:+1:

2019-10-30 04:49 UTC, chyku commented on frontend/src/components/app.js
>          <Route path="/map" component={MapBox} />
It'd be great if we could make the main path the path to the map

2019-10-30 04:49 UTC, chyku commented on frontend/src/resources/stateLayers.js
> +export default stateLayer;
pls run `npm run format` i'll add ci tests for this later lol

2019-10-30 05:01 UTC, chyku approved these changes

2019-10-30 05:03 UTC, arpanlaha approved these changes
🍪

2019-10-30 05:04 UTC, caiyingshen approved these changes
🤓

2019-10-30 05:06 UTC, coconut750750 approved these changes

2019-10-30 05:06 UTC, merged