Get endpoints
hack4impact-uiuc/communityconnect-labs pull request #14
Opened 2019-10-28 00:22 UTC by alanren2

2019-10-28 00:37 UTC, coconut750750 commented
what are these commits?!?!?!?!?!

2019-10-28 00:40 UTC, caiyingshen commented on backend/api/views/main.py
> +def get_census_response():
could you make the endpoint name more descriptive of what the query & params are?

2019-10-29 23:19 UTC, chyku reviewed
btw can you put an example response in the description?

2019-10-30 03:49 UTC, caiyingshen approved these changes
😱

2019-10-30 03:55 UTC, chyku requested changes

2019-10-30 03:55 UTC, chyku commented on backend/api/views/main.py
> +@main.route("/census_response_by_datetime", methods=["GET"])
can we make the url something like `/census_response?datetime="jdskflsdjkl"` bc this endpoint name is tilting me

2019-10-30 04:00 UTC, chyku approved these changes

2019-10-30 04:01 UTC, merged