Add api-wrapper
hack4impact-uiuc/communityconnect-labs pull request #15
Opened 2019-10-28 00:31 UTC by yousefa00

Added api-wrapper in utils directory. Using a log to test in map component.
Resolves #13

2019-10-29 21:48 UTC, chyku requested changes
just 1 tiny thing but great job!!

2019-10-29 21:48 UTC, chyku commented on frontend/src/components/mapbox.js
> +    console.log(getResponseByTractID("0"));
Add a `// TODO` comment so we know to remove this later!

2019-10-29 21:48 UTC, chyku commented on frontend/src/utils/apiWrapper.js
> +   */
great commenting!!

2019-10-29 21:48 UTC, chyku commented on frontend/src/utils/apiWrapper.js
> +export default getResponseByTractID;
it's really weird that you had to add this at the end but we'll see if we can fix this later

2019-10-30 03:45 UTC, chyku commented on frontend/src/components/mapbox.js
> +    // TODO: Replace the log below with a valid tract request
nice comment i rlly appreciate this

2019-10-30 03:46 UTC, chyku approved these changes
nice comment i rlly appreciate this

2019-10-30 03:53 UTC, caiyingshen approved these changes
🤓

2019-10-30 03:54 UTC, merged