Add number days after initial census collection to schema
hack4impact-uiuc/communityconnect-labs pull request #17
Opened 2019-10-30 05:17 UTC by alanren2

The rates dict struct now goes: year -> date -> list of rate and days after.

2019-10-30 17:29 UTC, chyku requested changes
1 thing for readability :ok_hand:

2019-10-30 17:29 UTC, chyku commented on backend/api/views/populate_db.py
> +    date_initial_obj = datetime.date(int(date_initial[-4:]), int(date_initial[:2]), int(date_initial[2:4]))
could you use `datetime.strptime('').date()` instead- it'd be more readable

2019-10-30 17:29 UTC, chyku commented on backend/api/views/populate_db.py
> +            date_obj = datetime.date(int(date[-4:]), int(date[:2]), int(date[2:4]))
same as above for parsing str into date obj

2019-10-30 17:29 UTC, chyku commented on backend/api/views/populate_db.py
> +                rates={"2010": {date: [rates[-1], delta.days]}},
bruh rip our db structure but its ok for mvp i guess

2019-11-02 20:09 UTC, chyku approved these changes
:ok_hand:

2019-11-02 20:18 UTC, caiyingshen approved these changes
😱

2019-11-06 04:32 UTC, merged