Parse census data
hack4impact-uiuc/communityconnect-labs pull request #3
Opened 2019-10-07 01:42 UTC by coconut750750

Resolves #2 
Added a Python script that takes a link and parses the census data into a Python object.

2019-10-07 01:49 UTC, chyku commented
[Data over different dates](https://www2.census.gov/programs-surveys/decennial/2010/program-management/4-release/mail-participation-rate/)

2019-10-17 23:46 UTC, coconut750750 commented
Added a new endpoint, `/census_response`, to the backend to accept a batch of Census Response Entries to populate the database.

Updated the script to use that endpoint to save Census Responses.

2019-10-20 23:04 UTC, chyku requested changes
Great work! I'm just clearing up some things I didn't clarify earlier, and it'd be great if you could put webpage parsing directly in the endpoint (which is p sus ik but idk if it'd be great to be parsing the page into a json file that you have to copy & paste manually)

Also I'm going to try to clean up the backend stuff so that there aren't a thousand changes

2019-10-20 23:04 UTC, chyku commented on backend/api/models/CensusResponse.py
> +    response_id = StringField(required=True)
By responseId, do you mean the tract Id? could we make this into a number-based field?

2019-10-20 23:04 UTC, chyku commented on backend/api/models/CensusResponse.py
> +    type = StringField(required=True)
These both should just be Tract and tract, as those are the only ones we're concerned with

2019-10-20 23:04 UTC, chyku commented on backend/api/views/main.py
> +    data = request.get_json()
Could we put the webpage parsing into this endpoint? I think it would be pretty hard to make the webpage data into a json format

2019-10-28 00:01 UTC, caiyingshen approved these changes
👻

looks good!! yay first PR!! 
(wait for kelley's approval before merging please)

2019-10-28 00:03 UTC, chyku requested changes
just tiny things

2019-10-28 00:03 UTC, chyku commented on backend/api/models/CensusResponse.py
> +    #     self.rate2010 = rate2010
pls update comment

2019-10-28 00:03 UTC, chyku commented on backend/api/views/web_scrap.py
> +    print(links)
no newline- can u go to backend into venv and run `black .`

2019-10-28 00:03 UTC, chyku commented on backend/api/views/populate_db.py
> +    # print(result.text)
clean up unused comments?

2019-10-28 00:14 UTC, chyku approved these changes

2019-10-28 00:15 UTC, merged