cluster works now
hack4impact-uiuc/communityconnect-labs pull request #33
Opened 2019-11-20 05:41 UTC by alanren2

2019-11-20 06:04 UTC, caiyingshen commented on backend/.env
> +MONGO_PASSWORD=Nfb1B0OoAK5ObeHP
pls take this out and send it to our channel so no one knows your password!!!

2019-11-20 06:06 UTC, caiyingshen requested changes

2019-11-20 06:06 UTC, caiyingshen commented on backend/.env
> +MONGO_PASSWORD=Nfb1B0OoAK5ObeHP
oops forgot to request changes

2019-12-04 04:23 UTC, chyku requested changes
:1st_place_medal:

2019-12-04 04:23 UTC, chyku commented on backend/.env
>  MONGO_DB=communityconnect-labs
could u remove this file and put it in the gitignore + put the contents into channel as a pinned post

2019-12-04 04:32 UTC, chyku approved these changes
:fire:

2019-12-04 05:17 UTC, caiyingshen approved these changes
beep beep 🤓

2019-12-04 05:21 UTC, merged